### ISSUE TITLE
Installation failure (but plugin still works)

### ISSUE THREAD

**Issue by mzealey** [nparashuram/cordova-plugin-browsersync#34]
This breaks the install (and hence platform add/remove), however it still works after it has installed

```
~/data/work/watchem/WatchEm/frontend$ cordova plugin add cordova-plugin-browsersync
Installing "cordova-plugin-browsersync" for android
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/cacache requires glob@'^7.1.2' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/flush-write-stream requires readable-stream@'^2.0.4' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.34
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/from2 requires readable-stream@'^2.0.0' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.34
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/globule requires glob@'~7.1.1' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/init-package-json requires glob@'^7.1.1' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/node-gyp requires glob@'^7.0.3' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/pacote requires glob@'^7.1.2' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/pacote requires safe-buffer@'^5.1.0' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/safe-buffer,
npm WARN unmet dependency which is version 5.0.1
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/parallel-transform requires readable-stream@'^2.1.5' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.34
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/read-package-json requires glob@'^7.1.1' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/sass-graph requires glob@'^7.0.0' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/sha requires readable-stream@'^2.0.2' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.34
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/ssri requires safe-buffer@'^5.1.0' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/safe-buffer,
npm WARN unmet dependency which is version 5.0.1
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/stream-iterate requires readable-stream@'^2.1.5' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.34
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/@ionic/cli-utils requires chalk@'^2.0.0' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/chalk,
npm WARN unmet dependency which is version 1.1.3
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/@ionic/cli-utils requires semver@'^5.4.1' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/semver,
npm WARN unmet dependency which is version 5.3.0
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/@ionic/cli-utils requires string-width@'^2.1.1' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/string-width,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/@ionic/cli-utils requires strip-ansi@'^4.0.0' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/strip-ansi,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/@ionic/cli-utils requires wrap-ansi@'^3.0.1' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/wrap-ansi,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/babel-cli requires glob@'^7.0.0' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/rimraf requires glob@'^7.0.5' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/webpack requires acorn@'^5.0.0' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/acorn,
npm WARN unmet dependency which is version 1.2.2
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/webpack requires ajv@'^5.1.5' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/ajv,
npm WARN unmet dependency which is version 4.11.8
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/webpack requires supports-color@'^4.2.1' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/supports-color,
npm WARN unmet dependency which is version 4.0.0
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/webpack requires yargs@'^8.0.2' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/yargs,
npm WARN unmet dependency which is version 7.1.0
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/archiver requires glob@'^7.0.0' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/archiver-utils requires glob@'^7.0.0' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/node-sass requires glob@'^7.0.3' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/tslint requires glob@'^7.1.1' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/duplexify requires readable-stream@'^2.0.0' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.34
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/mississippi/node_modules/through2 requires readable-stream@'^2.1.5' but will load
npm WARN unmet dependency /home/mark/data/work/watchem/WatchEm/frontend/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.34
Failed to install 'cordova-plugin-browsersync': Error: The package ajv@4.11.8 does not satisfy its siblings' peerDependencies requirements!
    at /home/mark/.npm/lib/node_modules/cordova/node_modules/npm/lib/install.js:125:32
    at /home/mark/.npm/lib/node_modules/cordova/node_modules/npm/lib/install.js:268:7
    at /home/mark/.npm/lib/node_modules/cordova/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
    at /home/mark/.npm/lib/node_modules/cordova/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/home/mark/.npm/lib/node_modules/cordova/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /home/mark/.npm/lib/node_modules/cordova/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/home/mark/.npm/lib/node_modules/cordova/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /home/mark/.npm/lib/node_modules/cordova/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/home/mark/.npm/lib/node_modules/cordova/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /home/mark/.npm/lib/node_modules/cordova/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
Error: The package ajv@4.11.8 does not satisfy its siblings' peerDependencies requirements!
```

**Comment by JackZhang1988** [comment]
I have same issue, what do you mean 'still works'?

**Comment by mzealey** [comment]
rerun it until it thinks its installed, then run it and it works as expected
